runtime: python
env: flex

entrypoint: gunicorn -b :$PORT main:app --worker-class eventlet -w 1 --timeout 0

runtime_config:
  python_version: 3

# This setting will use only 1 instance.
# Increase if you need more capacity.
manual_scaling:
  instances: 1

# Adjust resources as needed
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Add this if you're using websockets
network:
  session_affinity: true